-- ============================================================
-- Site composition: which photo fills which slot.
--
-- WHY THIS EXISTS
-- Alwin picks the images on the site himself, from /admin, and expects
-- it to go live. That was impossible while the choices lived in
-- TypeScript: homeStrip, heroPhoto and PHOTO_ROWS are git files, so a
-- change meant a commit and a deploy, which is the thing he was trying
-- to stop doing. These tables move the choices into the database, which
-- /admin writes and the public pages read.
--
-- The rule that shapes this schema: a bad row must never blank a page.
-- Every read path is written so that an absent, empty or partly-broken
-- row falls back to the committed defaults. See GET THE DEFAULTS in the
-- queries below.
--
-- "slot" is the unit. One row = one position on one page. That makes
-- ordering a plain integer sort with no special cases, and it means a
-- strip of 6 and a wall row of 2 use the same table.
-- ============================================================

-- 1. Composition ----------------------------------------------------
-- One row per chosen image per slot. `page` says which page the choice
-- belongs to; `slot_key` says which position on that page.
create table if not exists public.composition (
  id         uuid primary key default gen_random_uuid(),
  page       text not null,
  slot_key   text not null,
  sort_order integer not null default 0,
  -- The photos.id this slot points at. Deliberately a plain uuid and NOT a
  -- foreign key with on delete cascade: deleting a photo must leave a hole the
  -- admin can SEE and repair, not silently renumber every slot below it.
  photo_id   uuid,
  filename   text,
  updated_at timestamptz default now(),
  unique (page, slot_key, sort_order)
);

create index if not exists composition_page_order_idx
  on public.composition (page, sort_order);

alter table public.composition enable row level security;

-- Everyone can read: the public pages need it, including signed-out visitors.
drop policy if exists "composition public read" on public.composition;
create policy "composition public read"
  on public.composition for select
  using (true);

-- Only admins write. This is the real gate for the whole picker.
drop policy if exists "composition admin insert" on public.composition;
create policy "composition admin insert"
  on public.composition for insert
  with check (public.is_admin());

drop policy if exists "composition admin update" on public.composition;
create policy "composition admin update"
  on public.composition for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "composition admin delete" on public.composition;
create policy "composition admin delete"
  on public.composition for delete
  using (public.is_admin());

-- 2. Seed from the committed defaults ------------------------------
-- The current git choices, so the site is IDENTICAL before and after this
-- table exists. If every read path falls back to defaults anyway, this is
-- belt and braces — but it means the mock has something real to show on
-- first load instead of an empty page.
--
-- homeStrip / heroPhoto come from src/config.ts.
-- GENERATED by tools/gen-composition-seed.py — do not hand-edit.
-- Source of truth: src/demo.ts (ids->filenames), src/rows.ts (the wall),
-- src/config.ts (homeStrip, heroPhoto). Regenerate after any of those change.
insert into public.composition (page, slot_key, sort_order, filename) values
  ('home', 'strip', 0, '22-img-0239.jpg'),
  ('home', 'strip', 1, '21-img-0234.jpg'),
  ('home', 'strip', 2, '18-img-0043.jpg'),
  ('home', 'strip', 3, '26-img-0253.jpg'),
  ('home', 'strip', 4, '46-img-0119.jpg'),
  ('home', 'strip', 5, '1-20240718113728-img-0065.jpg'),
  ('home', 'hero', 0, '27-img-0297.jpg'),
  ('portfolio', 'wall', 0, '2-20240718114526-img-0124.jpg'),
  ('portfolio', 'wall', 1, '18-img-0043.jpg'),
  ('portfolio', 'wall', 2, '34-img-0461.jpg'),
  ('portfolio', 'wall', 3, '53-img-0155.jpg'),
  ('portfolio', 'wall', 4, '19-img-0198-3.jpg'),
  ('portfolio', 'wall', 5, '47-img-0121.jpg'),
  ('portfolio', 'wall', 6, '24-img-0245.jpg'),
  ('portfolio', 'wall', 7, '44-img-0098.jpg'),
  ('portfolio', 'wall', 8, '28-img-0308.jpg'),
  ('portfolio', 'wall', 9, '51-img-0145.jpg'),
  ('portfolio', 'wall', 10, '25-img-0249.jpg'),
  ('portfolio', 'wall', 11, '49-img-0131.jpg'),
  ('portfolio', 'wall', 12, '32-img-0404.jpg'),
  ('portfolio', 'wall', 13, '5-img-0086.jpg'),
  ('portfolio', 'wall', 14, '50-img-0143.jpg'),
  ('portfolio', 'wall', 15, '15-img-0025.jpg'),
  ('portfolio', 'wall', 16, '45-img-0118.jpg'),
  ('portfolio', 'wall', 17, '30-img-0396.jpg'),
  ('portfolio', 'wall', 18, '41-img-0094.jpg'),
  ('portfolio', 'wall', 19, '20-img-0202.jpg'),
  ('portfolio', 'wall', 20, '40-img-0092.jpg'),
  ('portfolio', 'wall', 21, '42-img-0095.jpg'),
  ('portfolio', 'wall', 22, '48-img-0128.jpg'),
  ('portfolio', 'wall', 23, '12-img-0019.jpg'),
  ('portfolio', 'wall', 24, '37-img-0124.jpg'),
  ('portfolio', 'wall', 25, '14-img-0026.jpg'),
  ('portfolio', 'wall', 26, '46-img-0119.jpg'),
  ('portfolio', 'wall', 27, '26-img-0253.jpg'),
  ('portfolio', 'wall', 28, '13-img-0020.jpg'),
  ('portfolio', 'wall', 29, '21-img-0234.jpg')
on conflict (page, slot_key, sort_order) do nothing;

-- 3. GET THE DEFAULTS, in one query ---------------------------------
-- The single read every public page uses. Note what it does NOT do:
-- it does not filter out rows whose photo_id is null or whose filename is
-- missing from the gallery. The caller resolves and validates, because only
-- the caller knows which pages tolerate a short row.
--
--   select * from public.composition
--   where page = 'home' and slot_key = 'strip'
--   order by sort_order;