import { defineConfig } from "vite";
import { resolve } from "node:path";

/**
 * Base path for asset URLs.
 *
 * The Pages workflow builds with BASE_PATH=./ (a relative base), so one build
 * resolves against the document and serves correctly at both the domain root
 * and the github.io project subpath. Default "/" is for local dev/preview.
 */
const base = process.env.BASE_PATH ?? "/";

/**
 * One input per page.
 *
 * Every route is a real document since 2026-10-02: before this, only `index`
 * and `admin` existed and `main.ts` swapped `#app` from `location.hash`, so a
 * crawler saw a single page for the whole site. Each html file below is
 * generated by tools/build-pages.py — edit the ROUTES list THERE, not here, so
 * the title/description/canonical for a page and its build input cannot drift
 * apart. Add a page in one place and re-run that script.
 */
const page = (name: string) => resolve(__dirname, name);

export default defineConfig({
  base,
  build: {
    outDir: "dist",
    rollupOptions: {
      input: {
        main: page("index.html"),
        portfolio: page("portfolio.html"),
        about: page("about.html"),
        services: page("services.html"),
        contact: page("contact.html"),
        admin: page("admin.html"),
      },
    },
  },
});
