"""
Generate src/shoots.ts — which shoot each gallery frame belongs to.

The column packer needs shoot membership at render time to keep two frames from
the same shoot off the top of neighbouring columns, and to sort the input
sequence the way the shoot-spread order does. The source of truth is
interleave-order.json, written by tools/shootorder.py.

Kept as a generated .ts rather than a JSON import so the bundler needs no
resolveJsonModule and so a missing/stale order file fails in the GENERATOR
(which already hard-fails) rather than at runtime.

Run: python tools/build-shoots-ts.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORDER = ROOT / "interleave-order.json"
OUT = ROOT / "src" / "shoots.ts"


def main() -> None:
    if not ORDER.exists():
        raise SystemExit(
            "interleave-order.json missing. Run: python tools/shootorder.py --write"
        )

    meta = json.loads(ORDER.read_text(encoding="utf-8"))
    shoot_of: dict[str, int] = meta["shoot_of"]
    order: list[str] = meta["order"]
    fingerprint = meta.get("fingerprint", "unknown")

    rows = "\n".join(
        f'  "{name}": {shoot_of[name]},' for name in order if name in shoot_of
    )

    doc = f'''/**
 * Which shoot each gallery frame came from.
 *
 * GENERATED by tools/build-shoots-ts.py from interleave-order.json — do not
 * hand-edit. `packByHeight()` reads this to keep two frames of one shoot out of
 * the top of neighbouring columns, which is what keeps the portfolio wall from
 * clumping the way the export order did.
 *
 * A frame not listed here is treated as its own shoot, so an unlisted file
 * cannot create a false "same shoot" neighbour.
 *
 * Order fingerprint: {fingerprint}
 */
export const SHOOT_OF: Record<string, number> = {{
{rows}
}};
'''
    OUT.write_text(doc, encoding="utf-8")
    print(f"{len(rows.splitlines())} frame(s) written to src/shoots.ts")


if __name__ == "__main__":
    main()