"""
Generate src/rows.ts — the 30 chosen frames, in row order.

GENERATED by tools/build-rows-ts.py from tools/rows.py. Do not hand-edit; edit
tools/rows.py and re-run.

Pinned to the gallery fingerprint so a stale rows.ts cannot ship against a
different set of photographs — the same discipline as demo.ts and curated.ts.

Run: python tools/build-rows-ts.py
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from rows import ROWS  # noqa: E402

DEMO = ROOT / "src" / "demo.ts"
OUT = ROOT / "src" / "rows.ts"

demo = DEMO.read_text(encoding="utf-8")
pairs = re.findall(r'id: "(c\d+)", url: "gallery/([^"]+)"', demo)
if not pairs:
    raise SystemExit("could not read id/filename pairs from src/demo.ts")
ids = [i for i, _ in pairs]
files = [f for _, f in pairs]
fingerprint = hashlib.sha1("\n".join(files).encode("utf-8")).hexdigest()[:16]

missing = [f for r in ROWS for f in r if f not in set(files)]
if missing:
    raise SystemExit("these frames are not in the gallery: " + ", ".join(missing))

rows_out = []
for row in ROWS:
    ids_out = ", ".join('"%s"' % ids[files.index(f)] for f in row)
    rows_out.append("  [%s] as PhotoRow," % ids_out)

doc = f"""import type {{ PhotoRow }} from "./types";

/**
 * The portfolio wall: 30 chosen frames, 10 rows of 3.
 *
 * GENERATED by tools/build-rows-ts.py from tools/rows.py — do not hand-edit.
 *
 * Alwin, 2026-10-01: no scroll on each column, static, no numbering on the
 * images, 30 of the best, 3 per row, "no spacing issues at all".
 *
 * Every row holds three frames of the EXACT same aspect ratio, so at a fixed
 * column width the three render at identical heights and each row is one clean
 * line with nothing cut and nothing stretched. tools/check-rows.py fails if a
 * row ever mixes ratios.
 *
 * Gallery fingerprint: {fingerprint}
 */
export const PHOTO_ROWS: PhotoRow[] = [
{chr(10).join(rows_out)}
];
"""
OUT.write_text(doc, encoding="utf-8")
(ROOT / "rows-fingerprint.json").write_text(
    json.dumps({"fingerprint": fingerprint, "gallery": len(files),
                "rows": len(ROWS), "frames": sum(len(r) for r in ROWS)}, indent=2),
    encoding="utf-8",
)
print("%d rows, %d frames -> %s  (fingerprint %s)"
      % (len(ROWS), sum(len(r) for r in ROWS), OUT.name, fingerprint))
