"""
Regenerate src/demo.ts from whatever is currently in public/gallery/.

Dimensions and filenames are read from the FILES, never hand-typed: the
srcset cap in `pictureFor()` depends on a correct `width`, and a wrong one
advertises a derivative that was never generated — which is what rendered
the home hero as a black box once already.

Ordering: natural filename order (the leading number Alwin's export used).
That number is the shoot order, so it is preserved.

Run: python tools/build-demo-ts.py
Idempotent — regenerates the file wholesale.
"""
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
DEMO = ROOT / "src" / "demo.ts"
GALLERY = ROOT / "public" / "gallery"

# Suffixes make-derivatives.py appends; only real originals belong here.
DERIV = re.compile(r"-\d+w\.(jpe?g|webp|png)$", re.I)


def main() -> None:
    files = [
        p for p in GALLERY.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png"} and not DERIV.search(p.name)
    ]
    # "1-foo.jpg", "10-foo.jpg" ... sort by the leading integer, not lexically,
    # so 2 comes before 10 the way the export numbered them.
    def key(p: Path):
        m = re.match(r"^(\d+)", p.stem)
        return (int(m.group(1)) if m else 10**9, p.stem)

    files.sort(key=key)

    rows = []
    for i, p in enumerate(files):
        w, h = Image.open(p).size
        slug = re.sub(r"[^a-z0-9]+", " ", p.stem.lower()).strip()
        rows.append(
            f'  {{ id: "c{i}", url: "gallery/{p.name}", '
            f'alt: "Portrait, natural light", album: "photo", '
            f"sort_order: {i}, visible: true, width: {w}, height: {h}, "
            f'filename: "{p.name}" }},'
        )

    doc = f'''import type {{ Photo }} from "./types";

/**
 * Alwin's favourites.
 *
 * Not a single shoot — these are the frames he picked out of everything he has
 * shot since he started. So there is no session narrative in the order; the
 * leading number is just the export order of the folder they were gathered in.
 *
 * GENERATED by tools/build-demo-ts.py from the files in public/gallery/ — do
 * not hand-edit. `width`/`height` are read from the actual images because
 * `pictureFor()` caps its srcset ladder at the source width, and a wrong value
 * advertises a derivative that does not exist (this shipped once as a black-box
 * hero).
 *
 * To add or reorder: change the files in public/gallery/, then
 *   python tools/build-demo-ts.py && python tools/make-derivatives.py
 *
 * The images live in public/gallery/ so the gallery looks right before
 * Supabase is connected. Uploads through /admin take over automatically.
 */
export const DEMO_PHOTOS: Photo[] = [
{chr(10).join(rows)}
];
'''
    DEMO.write_text(doc, encoding="utf-8")
    print(f"{len(rows)} photo(s) written to src/demo.ts")


if __name__ == "__main__":
    main()
