"""
Every candidate the srcset advertises must exist on disk.

    python tools/check-srcset.py

Why this exists
---------------
`src/pages.ts` builds each srcset with `w <= sourceWidth`, so a 1600px source
advertises a 1600w candidate. `tools/make-derivatives.py` used to generate only
`w < im.width`. The two disagreed for exactly-equal widths, and 16 of the 50
frames shipped advertising a file that was never written.

The browser trusted the srcset, requested -1600w.webp, got a 404, and fell back
to the full-size original — 604kB fetched for three visible frames, on
production. Nothing caught it: check-images.mjs asserts the images that DO load
are intact, so a 404 on the preferred candidate is invisible to it.

NO PILLOW, DELIBERATELY
-----------------------
This runs inside `npm run build`, which is what CI runs. An earlier version
imported PIL to read each image's width and the deploy failed with
`ModuleNotFoundError: No module named 'PIL'` — GitHub's runners do not have it,
and the other PIL tools in this folder are all local-only.

Widths are read from `src/demo.ts` instead. That file is GENERATED by
tools/build-demo-ts.py (which does use PIL, locally) and records the real
measured width of every frame, so nothing is lost. It is also a better source
than the pixels: the srcset is capped by the width written there, so the two
cannot disagree.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GALLERY = ROOT / "public" / "gallery"
DEMO = ROOT / "src" / "demo.ts"
EXTS = (".jpg", ".jpeg", ".png")

src_pages = (ROOT / "src" / "pages.ts").read_text(encoding="utf-8")
m = re.search(r"const WIDTHS = \[([^\]]+)\]", src_pages)
if not m:
    raise SystemExit("could not find WIDTHS in src/pages.ts — update this check")
WIDTHS = tuple(int(x) for x in re.findall(r"\d+", m.group(1)))

if not DEMO.exists():
    raise SystemExit(
        f"{DEMO.name} is missing. Run: python tools/build-demo-ts.py\n"
        "It records each frame's real width, which is what this check reads."
    )

demo = DEMO.read_text(encoding="utf-8")
# url + filename + the measured width, exactly as build-demo-ts.py writes them.
rows = re.findall(
    r'url: "gallery/([^"]+)"[\s\S]*?width: (\d+), height: (\d+)', demo
)
if not rows:
    raise SystemExit(f"no photo rows parsed out of {DEMO.name} — has its format changed?")

missing: list[str] = []
checked = 0
unreadable: list[str] = []

for filename, w, _h in rows:
    width = int(w)
    # The generator keeps originals next to their derivatives. If the original
    # is gone the frame was removed without regenerating; the derivative check
    # below will catch it, so just note it and keep going.
    if not any((GALLERY / filename).with_suffix(e).exists() for e in EXTS):
        unreadable.append(filename)
        continue
    for width_step in WIDTHS:
        if width_step > width:
            continue  # srcset caps at source width, so never advertised
        checked += 1
        stem = filename.rsplit(".", 1)[0]
        for ext in ("webp", "jpg"):
            if not (GALLERY / f"{stem}-{width_step}w.{ext}").exists():
                missing.append(f"{stem}-{width_step}w.{ext}")

print(f"{len(rows)} frame(s) in {DEMO.name}, {checked} advertised candidate(s) checked")

if unreadable:
    print(f"FAIL  {len(unreadable)} frame(s) in demo.ts have no file in public/gallery:")
    for f in unreadable[:10]:
        print("   ", f)
    print("   Re-run: python tools/build-demo-ts.py && python tools/make-derivatives.py")

if missing:
    print(f"FAIL  {len(missing)} advertised derivative(s) do not exist:")
    for f in missing[:20]:
        print("   ", f)
    print()
    print("Fix: python tools/make-derivatives.py")
    print("It must cover every width the srcset advertises — see the inclusive")
    print("`w <= im.width` note in that file for why the bound is not `<`.")

if missing or unreadable:
    sys.exit(1)

print("ok    every candidate the srcset advertises exists on disk")
