"""
Regenerate the composition seed in supabase/composition.sql.

The seed is the site's CURRENT image choices, read from the three files that
own them, so that a fresh database starts identical to what git already
serves:

    src/demo.ts     id -> filename
    src/rows.ts     the portfolio wall, 15 rows of 2
    src/config.ts   homeStrip and heroPhoto

Why a generator rather than a hand-written INSERT: the first hand-written
version of this file guessed 30 filenames, and every one of them was wrong.
A seed that silently names photos that do not exist produces a site that
renders holes, and the error surfaces on the public page rather than at the
point of the mistake. So the ids are resolved here and unresolved ids are a
hard failure, not a NULL.

Run: python tools/gen-composition-seed.py          (prints the seed)
     python tools/gen-composition-seed.py --check  (verify it is up to date)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def demo_files() -> dict[str, str]:
    """id -> filename, from the committed gallery manifest."""
    return dict(
        re.findall(r'id: "(c\d+)", url: "gallery/([^"]+)"', read("src/demo.ts"))
    )


def wall_rows() -> list[list[str]]:
    """The portfolio wall as a list of rows of frame ids."""
    rows = re.findall(r"\[([^\]]+)\]", read("src/rows.ts"))
    return [re.findall(r'"(c\d+)"', r) for r in rows]


def home_choices() -> tuple[list[str], str]:
    """(homeStrip, heroPhoto) from src/config.ts."""
    cfg = read("src/config.ts")
    strip = re.findall(
        r'"([^"]+\.jpg)"',
        re.search(r"homeStrip:\s*\[(.*?)\]", cfg, re.S).group(1),
    )
    hero = re.search(r'heroPhoto:\s*"([^"]+)"', cfg).group(1)
    return strip, hero


def build() -> str:
    files = demo_files()
    rows = wall_rows()
    strip, hero = home_choices()

    # Hard-fail on anything unresolvable. A seed with a wrong filename is worse
    # than no seed: it renders a hole in the middle of the wall.
    unresolved = [i for r in rows for i in r if i not in files]
    if unresolved:
        raise SystemExit(
            "these wall ids are not in demo.ts, so their filenames cannot be "
            f"resolved: {', '.join(unresolved)}"
        )

    out = [
        "-- GENERATED by tools/gen-composition-seed.py — do not hand-edit.",
        "-- Source of truth: src/demo.ts (ids->filenames), src/rows.ts (the wall),",
        "-- src/config.ts (homeStrip, heroPhoto). Regenerate after any of those change.",
        "insert into public.composition (page, slot_key, sort_order, filename) values",
    ]

    vals = [f"  ('home', 'strip', {i}, {q(f)})" for i, f in enumerate(strip)]
    vals.append(f"  ('home', 'hero', 0, {q(hero)})")
    for ri, row in enumerate(rows):
        for pi, cid in enumerate(row):
            vals.append(f"  ('portfolio', 'wall', {ri * 2 + pi}, {q(files[cid])})")
    out.append(",\n".join(vals))
    out.append("on conflict (page, slot_key, sort_order) do nothing;")
    return "\n".join(out)


def main() -> int:
    seed = build()
    target = ROOT / "supabase" / "composition.sql"

    if "--check" in sys.argv:
        if seed in target.read_text(encoding="utf-8"):
            print("ok  composition.sql seed is up to date")
            return 0
        print("FAIL  composition.sql seed is stale — rerun without --check")
        return 1

    print(seed)
    print(f"\n-- {len(seed.splitlines())} lines; not written. Paste into composition.sql", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())