import type { Photo } from "./types";

/**
 * Alwin's favourites.
 *
 * Not a single shoot — these are the frames he picked out of everything he has
 * shot since he started. So there is no session narrative in the order; the
 * leading number is just the export order of the folder they were gathered in.
 *
 * GENERATED by tools/build-demo-ts.py from the files in public/gallery/ — do
 * not hand-edit. `width`/`height` are read from the actual images because
 * `pictureFor()` caps its srcset ladder at the source width, and a wrong value
 * advertises a derivative that does not exist (this shipped once as a black-box
 * hero).
 *
 * To add or reorder: change the files in public/gallery/, then
 *   python tools/build-demo-ts.py && python tools/make-derivatives.py
 *
 * The images live in public/gallery/ so the gallery looks right before
 * Supabase is connected. Uploads through /admin take over automatically.
 */
export const DEMO_PHOTOS: Photo[] = [
  { id: "c0", url: "gallery/1-20240718113728-img-0065.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 0, visible: true, width: 2400, height: 1350, filename: "1-20240718113728-img-0065.jpg" },
  { id: "c1", url: "gallery/2-20240718114526-img-0124.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 1, visible: true, width: 1600, height: 2400, filename: "2-20240718114526-img-0124.jpg" },
  { id: "c2", url: "gallery/4-img-0068.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 2, visible: true, width: 2400, height: 1800, filename: "4-img-0068.jpg" },
  { id: "c3", url: "gallery/5-img-0086.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 3, visible: true, width: 1600, height: 2400, filename: "5-img-0086.jpg" },
  { id: "c4", url: "gallery/6-img-0161.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 4, visible: true, width: 2400, height: 1500, filename: "6-img-0161.jpg" },
  { id: "c5", url: "gallery/7-img-0207.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 5, visible: true, width: 2400, height: 1500, filename: "7-img-0207.jpg" },
  { id: "c6", url: "gallery/8-img-0268.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 6, visible: true, width: 2400, height: 1801, filename: "8-img-0268.jpg" },
  { id: "c7", url: "gallery/9-img-0269.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 7, visible: true, width: 1736, height: 2170, filename: "9-img-0269.jpg" },
  { id: "c8", url: "gallery/11-img-0018.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 8, visible: true, width: 1934, height: 2400, filename: "11-img-0018.jpg" },
  { id: "c9", url: "gallery/12-img-0019.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 9, visible: true, width: 1600, height: 2400, filename: "12-img-0019.jpg" },
  { id: "c10", url: "gallery/13-img-0020.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 10, visible: true, width: 1600, height: 2400, filename: "13-img-0020.jpg" },
  { id: "c11", url: "gallery/14-img-0026.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 11, visible: true, width: 1600, height: 2400, filename: "14-img-0026.jpg" },
  { id: "c12", url: "gallery/15-img-0025.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 12, visible: true, width: 1600, height: 2400, filename: "15-img-0025.jpg" },
  { id: "c13", url: "gallery/16-img-0030.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 13, visible: true, width: 1600, height: 2400, filename: "16-img-0030.jpg" },
  { id: "c14", url: "gallery/18-img-0043.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 14, visible: true, width: 1600, height: 2400, filename: "18-img-0043.jpg" },
  { id: "c15", url: "gallery/19-img-0198-3.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 15, visible: true, width: 1920, height: 2400, filename: "19-img-0198-3.jpg" },
  { id: "c16", url: "gallery/20-img-0202.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 16, visible: true, width: 1350, height: 2400, filename: "20-img-0202.jpg" },
  { id: "c17", url: "gallery/21-img-0234.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 17, visible: true, width: 1600, height: 2400, filename: "21-img-0234.jpg" },
  { id: "c18", url: "gallery/22-img-0239.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 18, visible: true, width: 2065, height: 2400, filename: "22-img-0239.jpg" },
  { id: "c19", url: "gallery/23-img-0240.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 19, visible: true, width: 1444, height: 2400, filename: "23-img-0240.jpg" },
  { id: "c20", url: "gallery/24-img-0245.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 20, visible: true, width: 1350, height: 2400, filename: "24-img-0245.jpg" },
  { id: "c21", url: "gallery/25-img-0249.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 21, visible: true, width: 1600, height: 2400, filename: "25-img-0249.jpg" },
  { id: "c22", url: "gallery/26-img-0253.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 22, visible: true, width: 1920, height: 2400, filename: "26-img-0253.jpg" },
  { id: "c23", url: "gallery/27-img-0297.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 23, visible: true, width: 2400, height: 1866, filename: "27-img-0297.jpg" },
  { id: "c24", url: "gallery/28-img-0308.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 24, visible: true, width: 1920, height: 2400, filename: "28-img-0308.jpg" },
  { id: "c25", url: "gallery/29-img-0383.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 25, visible: true, width: 1760, height: 2400, filename: "29-img-0383.jpg" },
  { id: "c26", url: "gallery/30-img-0396.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 26, visible: true, width: 1920, height: 2400, filename: "30-img-0396.jpg" },
  { id: "c27", url: "gallery/31-img-0397.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 27, visible: true, width: 1871, height: 2400, filename: "31-img-0397.jpg" },
  { id: "c28", url: "gallery/32-img-0404.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 28, visible: true, width: 1600, height: 2400, filename: "32-img-0404.jpg" },
  { id: "c29", url: "gallery/33-img-0426.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 29, visible: true, width: 2092, height: 2400, filename: "33-img-0426.jpg" },
  { id: "c30", url: "gallery/34-img-0461.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 30, visible: true, width: 1350, height: 2400, filename: "34-img-0461.jpg" },
  { id: "c31", url: "gallery/35-img-0482.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 31, visible: true, width: 1920, height: 2400, filename: "35-img-0482.jpg" },
  { id: "c32", url: "gallery/36-img-0076.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 32, visible: true, width: 1600, height: 2400, filename: "36-img-0076.jpg" },
  { id: "c33", url: "gallery/37-img-0124.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 33, visible: true, width: 1600, height: 2400, filename: "37-img-0124.jpg" },
  { id: "c34", url: "gallery/38-img-0087.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 34, visible: true, width: 1417, height: 2400, filename: "38-img-0087.jpg" },
  { id: "c35", url: "gallery/39-img-0089.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 35, visible: true, width: 1730, height: 2400, filename: "39-img-0089.jpg" },
  { id: "c36", url: "gallery/40-img-0092.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 36, visible: true, width: 1920, height: 2400, filename: "40-img-0092.jpg" },
  { id: "c37", url: "gallery/41-img-0094.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 37, visible: true, width: 1350, height: 2400, filename: "41-img-0094.jpg" },
  { id: "c38", url: "gallery/42-img-0095.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 38, visible: true, width: 1920, height: 2400, filename: "42-img-0095.jpg" },
  { id: "c39", url: "gallery/43-img-0096.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 39, visible: true, width: 1317, height: 2400, filename: "43-img-0096.jpg" },
  { id: "c40", url: "gallery/44-img-0098.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 40, visible: true, width: 1350, height: 2400, filename: "44-img-0098.jpg" },
  { id: "c41", url: "gallery/45-img-0118.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 41, visible: true, width: 1920, height: 2400, filename: "45-img-0118.jpg" },
  { id: "c42", url: "gallery/46-img-0119.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 42, visible: true, width: 1920, height: 2400, filename: "46-img-0119.jpg" },
  { id: "c43", url: "gallery/47-img-0121.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 43, visible: true, width: 1920, height: 2400, filename: "47-img-0121.jpg" },
  { id: "c44", url: "gallery/48-img-0128.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 44, visible: true, width: 1600, height: 2400, filename: "48-img-0128.jpg" },
  { id: "c45", url: "gallery/49-img-0131.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 45, visible: true, width: 1600, height: 2400, filename: "49-img-0131.jpg" },
  { id: "c46", url: "gallery/50-img-0143.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 46, visible: true, width: 1600, height: 2400, filename: "50-img-0143.jpg" },
  { id: "c47", url: "gallery/51-img-0145.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 47, visible: true, width: 1920, height: 2400, filename: "51-img-0145.jpg" },
  { id: "c48", url: "gallery/52-img-0149.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 48, visible: true, width: 1350, height: 2400, filename: "52-img-0149.jpg" },
  { id: "c49", url: "gallery/53-img-0155.jpg", alt: "Portrait, natural light", album: "photo", sort_order: 49, visible: true, width: 1350, height: 2400, filename: "53-img-0155.jpg" },
];
