import type { PhotoRow } from "./types";

/**
 * The portfolio wall: 15 chosen frames, 15 rows of 2.
 *
 * GENERATED by tools/build-rows-ts.py from tools/rows.py — do not hand-edit.
 *
 * Alwin, 2026-10-01: no scroll on each column, static, no numbering on the
 * images, 30 of the best, 3 per row, "no spacing issues at all".
 *
 * Alwin, 2026-10-02: two per row, because three columns at 393px gave 111px
 * tiles — too small to read a face. The COLUMN COUNT is owned by the CSS as a
 * viewport concern; it used to be derived from the row length here, which
 * dragged the desktop to two columns as well and made the page 14,582px tall.
 * If you are changing this file by hand, you are in the wrong place: edit
 * tools/rows.py, which is the source, and regenerate.
 *
 * Every row holds two frames of the EXACT same aspect ratio, so at a fixed
 * column width the two render at identical heights and each row is one clean
 * line with nothing cut and nothing stretched. tools/check-rows.py fails if a
 * row ever mixes ratios.
 *
 * Gallery fingerprint: 1b1c1d9e00e6f4ea
 */
export const PHOTO_ROWS: PhotoRow[] = [
  ["c46", "c34"] as PhotoRow,
  ["c21", "c47"] as PhotoRow,
  ["c23", "c37"] as PhotoRow,
  ["c18", "c1"] as PhotoRow,
  ["c8", "c36"] as PhotoRow,
  ["c4", "c15"] as PhotoRow,
  ["c32", "c41"] as PhotoRow,
  ["c12", "c10"] as PhotoRow,
  ["c0", "c35"] as PhotoRow,
  ["c48", "c45"] as PhotoRow,
  ["c7", "c31"] as PhotoRow,
  ["c30", "c25"] as PhotoRow,
  ["c19", "c42"] as PhotoRow,
  ["c11", "c44"] as PhotoRow,
  ["c40", "c6"] as PhotoRow,
];
