import type { PhotoRow } from "./types";

/**
 * The portfolio wall: 15 chosen frames, 15 rows of 2.
 *
 * GENERATED by tools/build-rows-ts.py from tools/rows.py — do not hand-edit.
 *
 * Alwin, 2026-10-01: no scroll on each column, static, no numbering on the
 * images, 30 of the best, 3 per row, "no spacing issues at all".
 *
 * Alwin, 2026-10-02: two per row, because three columns at 393px gave 111px
 * tiles — too small to read a face. The COLUMN COUNT is owned by the CSS as a
 * viewport concern; it used to be derived from the row length here, which
 * dragged the desktop to two columns as well and made the page 14,582px tall.
 * If you are changing this file by hand, you are in the wrong place: edit
 * tools/rows.py, which is the source, and regenerate.
 *
 * Every row holds two frames of the EXACT same aspect ratio, so at a fixed
 * column width the two render at identical heights and each row is one clean
 * line with nothing cut and nothing stretched. tools/check-rows.py fails if a
 * row ever mixes ratios.
 *
 * Gallery fingerprint: dfd93a5a1b0883bb
 */
export const PHOTO_ROWS: PhotoRow[] = [
  ["c47", "c44"] as PhotoRow,
  ["c34", "c39"] as PhotoRow,
  ["c38", "c42"] as PhotoRow,
  ["c9", "c11"] as PhotoRow,
  ["c31", "c0"] as PhotoRow,
  ["c33", "c5"] as PhotoRow,
  ["c6", "c43"] as PhotoRow,
  ["c48", "c21"] as PhotoRow,
  ["c32", "c3"] as PhotoRow,
  ["c29", "c1"] as PhotoRow,
  ["c26", "c8"] as PhotoRow,
  ["c45", "c24"] as PhotoRow,
  ["c15", "c10"] as PhotoRow,
  ["c20", "c30"] as PhotoRow,
  ["c51", "c22"] as PhotoRow,
];
