import type { PhotoRow } from "./types";

/**
 * The portfolio wall: 30 chosen frames, 10 rows of 3.
 *
 * GENERATED by tools/build-rows-ts.py from tools/rows.py — do not hand-edit.
 *
 * Alwin, 2026-10-01: no scroll on each column, static, no numbering on the
 * images, 30 of the best, 3 per row, "no spacing issues at all".
 *
 * Every row holds three frames of the EXACT same aspect ratio, so at a fixed
 * column width the three render at identical heights and each row is one clean
 * line with nothing cut and nothing stretched. tools/check-rows.py fails if a
 * row ever mixes ratios.
 *
 * Gallery fingerprint: 417a95692b6bd627
 */
export const PHOTO_ROWS: PhotoRow[] = [
  ["c0", "c10", "c31"] as PhotoRow,
  ["c2", "c19", "c24"] as PhotoRow,
  ["c1", "c15", "c21"] as PhotoRow,
  ["c17", "c22", "c32"] as PhotoRow,
  ["c11", "c46", "c45"] as PhotoRow,
  ["c3", "c4", "c7"] as PhotoRow,
  ["c9", "c30", "c39"] as PhotoRow,
  ["c18", "c23", "c42"] as PhotoRow,
  ["c13", "c44", "c8"] as PhotoRow,
  ["c12", "c36", "c29"] as PhotoRow,
];
