/**
 * Which shoot each gallery frame came from.
 *
 * GENERATED by tools/build-shoots-ts.py from interleave-order.json — do not
 * hand-edit. `packByHeight()` reads this to keep two frames of one shoot out of
 * the top of neighbouring columns, which is what keeps the portfolio wall from
 * clumping the way the export order did.
 *
 * A frame not listed here is treated as its own shoot, so an unlisted file
 * cannot create a false "same shoot" neighbour.
 *
 * Order fingerprint: e3a02f4be9e33496
 */
export const SHOOT_OF: Record<string, number> = {
  "49-img-0131.jpg": 16,
  "32-img-0404.jpg": 2,
  "14-img-0026.jpg": 8,
  "26-img-0253.jpg": 13,
  "40-img-0092.jpg": 16,
  "4-img-0068.jpg": 2,
  "11-img-0018.jpg": 3,
  "42-img-0095.jpg": 16,
  "9-img-0269.jpg": 7,
  "30-img-0396.jpg": 2,
  "48-img-0128.jpg": 16,
  "36-img-0076.jpg": 8,
  "24-img-0245.jpg": 2,
  "47-img-0121.jpg": 16,
  "29-img-0383.jpg": 14,
  "37-img-0124.jpg": 15,
  "38-img-0087.jpg": 16,
  "16-img-0030.jpg": 2,
  "19-img-0198-3.jpg": 10,
  "15-img-0025.jpg": 8,
  "39-img-0089.jpg": 16,
  "21-img-0234.jpg": 2,
  "12-img-0019.jpg": 3,
  "51-img-0145.jpg": 16,
  "18-img-0043.jpg": 9,
  "23-img-0240.jpg": 2,
  "1-20240718113728-img-0065.jpg": 0,
  "41-img-0094.jpg": 16,
  "33-img-0426.jpg": 2,
  "20-img-0202.jpg": 11,
  "45-img-0118.jpg": 16,
  "25-img-0249.jpg": 2,
  "13-img-0020.jpg": 3,
  "43-img-0096.jpg": 16,
  "27-img-0297.jpg": 2,
  "6-img-0161.jpg": 4,
  "53-img-0155.jpg": 16,
  "34-img-0461.jpg": 3,
  "31-img-0397.jpg": 2,
  "46-img-0119.jpg": 16,
  "8-img-0268.jpg": 6,
  "22-img-0239.jpg": 12,
  "28-img-0308.jpg": 3,
  "52-img-0149.jpg": 16,
  "35-img-0482.jpg": 2,
  "2-20240718114526-img-0124.jpg": 1,
  "50-img-0143.jpg": 16,
  "5-img-0086.jpg": 3,
  "7-img-0207.jpg": 5,
  "44-img-0098.jpg": 16,
};
